rename issuer name on 1095A forms as approved by ME
ideacrew/polypress pull request #124
Opened 2023-12-04 21:48 UTC by saipraveen18

https://www.pivotaltracker.com/story/show/186528262

2023-12-05 14:49 UTC, saikumar9 approved these changes
lgtm!

2023-12-05 14:52 UTC, saikumar9 requested changes

2023-12-05 14:52 UTC, saikumar9 commented on app/models/irs_yearly_pdf_report.rb
> +  def fetch_insurance_provider_title(title)
@saipraveen18 This code should only work for the client ME and not for DC. We need to use the resource registry or the existing implemented pattern to ensure there is different behavior b/w clients.

2023-12-06 14:49 UTC, saikumar9 approved these changes
lgtm!

2023-12-06 14:56 UTC, vkghub approved these changes
LGTM

2023-12-06 14:56 UTC, merged