updates to honor communication preference for OE notice
ideacrew/polypress pull request #36
Opened 2022-01-13 17:39 UTC by Battula

[180463907](https://www.pivotaltracker.com/story/show/180463907)

2022-01-13 18:22 UTC, saikumar9 approved these changes

2022-01-14 16:02 UTC, markgoho requested changes
@Battula please ensure an update to aca_entities doesn't also update a bunch of other dependencies

2022-01-14 17:09 UTC, Battula commented
@markgoho ready to merge!

2022-01-14 19:09 UTC, markgoho approved these changes

2022-01-14 19:09 UTC, merged